apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
spec:
  serviceName: "movie-db"
  replicas: {{ .Values.movie_db.replicas | default 1 }}
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: {{ .Values.movie_db.image }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.movie_db.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.movie_db.password }}
        - name: POSTGRES_DB
          value: {{ .Values.movie_db.database }}
        ports:
        - containerPort: {{ .Values.movie_db.port }}
        volumeMounts:
        - name: movie-db-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: movie-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.movie_db.persistence.size | default "1Gi" }}
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  selector:
    app: movie-db
  ports:
    - protocol: TCP
      port: {{ .Values.movie_db.port }}
      targetPort: {{ .Values.movie_db.port }}
